### ISSUE TITLE
Maximum number of nodes that can be handled

### ISSUE THREAD

**Issue by Vini2** [austenb28/CycFlowDec#1]
Hello! 

Thank you for developing this code. I found it very interesting.

I was wondering if you have a recommended number of nodes the code can handle on a machine with 16GB of RAM? I would like to use it on more complex networks with over 100 nodes. I would really appreciate your thoughts regarding memory usage.

Thank you!

**Comment by austenb28** [comment]
Hi Vijini,

I'm glad you are interested in using CycFlowDec.  We did not perform extensive testing for the maximum number of nodes the code can handle, as this will depend on quite a few variables.  However, there are strategies you can use to test the feasibility of using CycFlowDec on your larger networks.

The most relevant parameter is likely the minimum contribution tolerance `tol` that is passed to the constructor `CycFlowDec(F,state,tol)`. This parameter must be between zero and one, with higher values resulting in shorter and fewer walk stacks, which will have faster iterations with lower memory requirements.  The performance gain comes at the cost of maximum achievable accuracy.  Appendix A.4, Appendix C, and Figure C.9 in reference 3 of the README have more information on `tol` and it's usage.  

I'd suggest testing your networks with a few values of `tol` (ex. `tol = 1E-1,1E-2,1E-3...`) at varying step numbers, while assessing the speed and accuracy (similar to Figure C.9 in reference 3).  When assessing accuracy with calc_MRE, be sure to use a tolerance that's greater than zero (actual value is network dependent, should be just lower than the smallest edge flow that you care about), as near-zero edge flows will dominate due to floating point error.  The 64-node code in the examples folder should be helpful for setting that up.

If you find that you cannot achieve acceptable performance on your large networks, you might consider using a node reduction algorithm to reduce the size of your network, and then run CycFlowDec on the smaller network.

I hope this information was helpful, let me know if you have other questions!

Best,
Austen

**Comment by Vini2** [comment]
Hi @austenb28,

Thank you very much for your detailed response. By setting `tol` to around `1E-10` I was able to run on my networks.
